[package]
name = "hyprland-better-share-picker"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.14.0"
smithay-client-toolkit = "0.20.0"
wayland-client = "0.31.11"
wayland-protocols-wlr = { version = "0.3.9", features = ["client"] }
wayland-scanner = "0.31.7"
